name: API Code quality

on:
  pull_request:
    branches:
      - master
    paths:
      - "api/**"
      - "!**.md"

jobs:
  api-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9
      - name: install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
      - name: cache pipenv
        id: cache-pipenv
        uses: actions/cache@v2.1.4
        with:
          path: |
            ~/.cache/pipenv
            test/api/.venv
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/api/Pipfile.lock') }}
      - name: install dependencies
        working-directory: ./api
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        env:
          PIPENV_VENV_IN_PROJECT: 1
        run: |
          pipenv install --dev
      - name: run tests
        working-directory: ./api
        env:
          PIPENV_VENV_IN_PROJECT: 1
        run: |
          pipenv run test || pipenv --rm && pipenv install --dev && pipenv run test
